# Generated by Django 4.0 on 2022-01-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок блога')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка на блог')),
                ('body', models.TextField(verbose_name='Тело блога')),
                ('private', models.BooleanField(default=True, verbose_name='Виден всем')),
            ],
        ),
    ]
